:w

diff --git a/word b/word
--- a/word
+++ b/word
@@ -19,7 +19,7 @@
 #########\
 
 # Print usage if no args or help asked
-read -r -d '' USAGE << 'EOF'
+read -r -d '' usage << 'EOF'
 Usage: word [options] [primary modifiers] <word|phrase> \
        [primary|secondary modifiers <word|phrase|number>]
 
@@ -50,21 +50,21 @@ Optionally, read <<CONTRIBUTING.md>> and open an issue,
 so I can fix it for the next person.
 
 EOF
-if [[ $# -eq 0 || $1 =~ (--help)|(-h) ]]; then echo "$USAGE"; exit 1; fi
+if [[ $# -eq 0 || $1 =~ (--help)|(-h) ]]; then echo "$usage"; exit 1; fi
 
 # Turn on verbose if flagged
 case $1 in
-    -v)   VERBOSE=1 ; shift ;;
-    -vv)  VERBOSE=2 ; shift ;;
-    -vvv) VERBOSE=3 ; shift ;;
-    -x)   DRY_RUN=1 ; VERBOSE=2 ; shift ;;
+    -v)   verbose=1 ; shift ;;
+    -vv)  verbose=2 ; shift ;;
+    -vvv) verbose=3 ; shift ;;
+    -x)   dry_run=1 ; verbose=2 ; shift ;;
 esac
 
 # Vars for creating the curl request
-API="datamuse"
-MAX=20
-PARAMS=("ml" "sl" "sp" "rel_jja" "rel_jjb" "rel_syn" "rel_trg" "rel_ant" "rel_spc" "rel_gen" "rel_com" "rel_par" "rel_bga" "rel_bgb" "rel_rhy" "rel_nry" "rel_hom" "rel_cns" "lc" "rc" "topics")
-GLOSS=("have a meaning like" "sound like" "are spelled like" "are used with the adjective" "are used with the noun" "are synonyms of" "are triggered by" "are antonyms of" "are a more general word for" "are a specific kind of" "are the parts of" "describe things made with" "usually follow" "usually preceed" "are perfect rhymes of" "are approximate rhymes of" "are homophones of" "have the same consonants as" "often follow" "often come before" "are about")
+api="datamuse"
+max=20
+params=("ml" "sl" "sp" "rel_jja" "rel_jjb" "rel_syn" "rel_trg" "rel_ant" "rel_spc" "rel_gen" "rel_com" "rel_par" "rel_bga" "rel_bgb" "rel_rhy" "rel_nry" "rel_hom" "rel_cns" "lc" "rc" "topics")
+gloss=("have a meaning like" "sound like" "are spelled like" "is a noun describing the adjective" "is an adjective describing the noun" "are synonyms of" "are triggered by" "are antonyms of" "are a more general word for" "are a specific kind of" "are the parts of" "describe things made with" "usually follow" "usually preceed" "are perfect rhymes of" "are approximate rhymes of" "are homophones of" "have the same consonants as" "often follow" "often come before" "are about")
 
 # Rhymes is hard to spell
 is_rhymes() {
@@ -91,23 +91,23 @@ is_pronounced() {
 # Convert to number
 convert_num() {
     case $1 in
-        one) USER_MAX=1 ;;
-        two) USER_MAX=2 ;;
-        three) USER_MAX=3 ;;
-        four) USER_MAX=4 ;;
-        five) USER_MAX=5 ;;
-        six) USER_MAX=6 ;;
-        seven) USER_MAX=7 ;;
-        eight) USER_MAX=8 ;;
-        nine) USER_MAX=9 ;;
-        ten) USER_MAX=10 ;;
-        *) USER_MAX=$(echo "$1" | sed 's/[^0-9]//')
+        one) user_max=1 ;;
+        two) user_max=2 ;;
+        three) user_max=3 ;;
+        four) user_max=4 ;;
+        five) user_max=5 ;;
+        six) user_max=6 ;;
+        seven) user_max=7 ;;
+        eight) user_max=8 ;;
+        nine) user_max=9 ;;
+        ten) user_max=10 ;;
+        *) user_max=$(echo "$1" | sed 's/[^0-9]//')
     esac
 }
 
 # Deliniate the end of a phrase
 stop_word() {
-    stop_words=("and" "no" "meaning" "means" "max" "about")
+    stop_words=("and" "no" "meaning" "means" "max" "about" "which" "that")
     for s in ${stop_words[@]}; do
         if [[ $1 = $s ]]; then
             return 0
@@ -116,17 +116,33 @@ stop_word() {
     return 1
 }
 
+go_curl() {
+    curl_res=$(curl -m 15 -sG "$1")
+    if [[ $? -ne 0 ]]; then
+        printf "\033[0;36mUnable to reach API.\033[0m Check your internet connection or try again with more feeling.\n"
+        exit 1
+    elif [[ $curl_res = "[]" && $api != "owlbot" ]]; then
+        if hash fortune 2>/dev/null; then
+            printf "\033[0;36mNo results found!\033[0m Have a fortune cookie:\n"
+            fortune -s
+        else
+            printf "\033[0;36mNo results found!\033[0m Try a paper dictionary instead?\n"
+        fi
+        exit 1
+    fi
+}
+
 # Deal first with the metadata flags
 case $# in
     2) if [[ $2 =~ defin(ed)|(ition) ]]; then
-           sp="$1"; API="owlbot"; shift 2
+           sp="$1"; api="owlbot"; shift 2
        elif is_pronounced $2; then
            sp="$1"; md="r"; shift 2
        fi ;;
-    3) if [[ "$1 $2" =~ defintion\ (of)|(for) ]]; then
-           sp="$3"; API="owlbot"; shift 3
+    3) if [[ "$1" = "definition" && "$2" =~ (of)|(for) ]]; then
+           sp="$3"; api="owlbot"; shift 3
        elif [[ "$2 $3" = "means what" ]]; then
-           sp="$1"; API="owlbot"; shift 3
+           sp="$1"; api="owlbot"; shift 3
        elif [[ $2 =~ (of)|(for) ]] && is_pronounced $1; then
            sp="$3"; md="r"; shift 3
        fi ;;
@@ -164,17 +180,17 @@ while [[ $# -gt 0 ]]; do
         sp="$2"
         shift 2
     elif [[ $# -gt 2 && $2 = "with" ]] && is_rhymes $1; then
-        shift 2
-        rel_rhy="$1"
-        shift
+        rel_rhy="$3"
+        shift 3
+    elif [[ $# -gt 3 && "$1 $3" = "almost with" ]] && is_rhymes $2; then
+        rel_nry="$4"
+        shift 4
 
-
-    elif [[ $1 = "comes" && $# -gt 2 ]]; then
-        if [[ $2 = "after" ]]; then
-            lc="$3"
-        elif [[ $2 = "before" ]]; then
-            rc="$3"
-        fi
+    elif [[ "$1 $2" = "comes after" && $# -gt 2 ]]; then
+        lc="$3"
+        shift 3
+    elif [[ "$1 $2" = "comes before" && $# -gt 2 ]]; then
+        rc="$3"
         shift 3
     elif [[ $1 = "follows" ]]; then
         lc="$2"
@@ -182,6 +198,15 @@ while [[ $# -gt 0 ]]; do
     elif [[ $1 = "preceeds" ]]; then
         rc="$2"
         shift 2
+    elif [[ $1 = "describes" ]]; then
+        rel_jjb="$2"
+        shift 2
+    elif [[ "$1 $2" = "associated with" && $# -gt 2 ]]; then
+        rel_trg="$3"
+        shift 3
+    elif [[ "$1 $2" = "triggered by" && $# -gt 2 ]]; then
+        rel_trg="$3"
+        shift 3
 
     elif [[ $1 = "means" || $1 = "meaning" || $1 = "like" ]]; then
         shift
@@ -202,8 +227,8 @@ while [[ $# -gt 0 ]]; do
     elif [[ $1 = "max" || $1 = "maximum" || $1 = "only" ]]; then
         convert_num $2
         shift 2
-        if [[ $USER_MAX -gt 1000 ]]; then
-            USER_MAX=1000
+        if [[ $user_max -gt 1000 ]]; then
+            user_max=1000
         fi
 
     # Remove filler words if they weren't parsed out above
@@ -222,72 +247,67 @@ while [[ $# -gt 0 ]]; do
 done # while [[ $# -gt 0 ]]
 
 # Build the curl request
-if [[ $API = "datamuse" && $md = "r" ]]; then
-    CURL_REQ="https://api.datamuse.com/words?max=1&sp=${sp}&qe=sp&md=r&ipa=1"
-    ASKED=("You asked for the pronunciation of '${sp}'.")
-elif [[ $API = "datamuse" ]]; then
-    CURL_REQ="https://api.datamuse.com/words?max=${USER_MAX:-"$MAX"}"
+if [[ $api = "datamuse" && $md = "r" ]]; then
+    curl_req="https://api.datamuse.com/words?max=1&sp=${sp}&qe=sp&md=r&ipa=1"
+    asked=("You asked for the pronunciation of '${sp}'.")
+elif [[ $api = "datamuse" ]]; then
+    curl_req="https://api.datamuse.com/words?max=${user_max:-"$max"}"
     # For each paramater, if it is defined, uri encode it and add it to the query string
-    for i in ${!PARAMS[@]}; do
-        if [[ -n ${!PARAMS[i]} ]]; then
-            CURL_REQ="${CURL_REQ}&${PARAMS[i]}=$(printf %s "${!PARAMS[i]}" | jq -s -R -r @uri)"
-            ASKED+=("and ${GLOSS[i]} '${!PARAMS[i]}'")
+    for i in ${!params[@]}; do
+        if [[ -n ${!params[i]} ]]; then
+            curl_req="${curl_req}&${params[i]}=$(printf %s "${!params[i]}" | jq -s -R -r @uri)"
+            asked+=("and ${gloss[i]} '${!params[i]}'")
         fi
     done
-    ASKED="You asked for words which $(echo "${ASKED[@]}" | sed -E 's/^and //')${USER_MAX:+", max $USER_MAX results"}."
-elif [[ $API = "owlbot" ]]; then
-    CURL_REQ="https://owlbot.info/api/v2/dictionary/$(echo "$sp" | sed -E "s/[^a-Z'-]*//g")"
-    ASKED=("You asked for the definition of '${sp}'.")
+    asked="You asked for words which $(echo "${asked[@]}" | sed -E 's/^and //')${user_max:+", max $user_max results"}."
+elif [[ $api = "owlbot" ]]; then
+    curl_req="https://owlbot.info/api/v2/dictionary/$(echo "$sp" | sed -E "s/[^a-Z'-]*//g")"
+    asked=("You asked for the definition of '${sp}'.")
 fi
 
 # Plain english description of our query
-if [[ $VERBOSE -gt 0 ]]; then
-    printf "%s\n" "$ASKED"
+if [[ $verbose -gt 0 ]]; then
+    printf "%s\n" "$asked"
 fi
 
 # What we are going to ask the remote server
-if [[ $VERBOSE -gt 1 ]]; then
-    printf "%s\n" "I ran curl -sG \"${CURL_REQ}\""
+if [[ $verbose -gt 1 ]]; then
+    printf "%s\n" "I ran curl -sG \"${curl_req}\""
 fi
 
-if [[ ! $DRY_RUN ]]; then
+if [[ ! $dry_run ]]; then
     # Ask away! (with a tiny bit of error handling)
-    CURL_RES=$(curl -m 15 -sG "$CURL_REQ")
-    if [[ $? -ne 0 ]]; then
-        printf "\033[0;36mUnable to reach API.\033[0m Check your internet connection or try again with more feeling.\n"
-        exit 1
-    elif [[ $CURL_RES = "[]" ]]; then
-        if hash fortune 2>/dev/null; then
-            printf "\033[0;36mNo results found!\033[0m Have a fortune cookie:\n"
-            fortune -s
-        else
-            printf "\033[0;36mNo results found!\033[0m Try a paper dictionary instead?\n"
-        fi
-        exit 1
-    fi
+    go_curl $curl_req
     
     # Parse and display return values
     if [[ $md = "r" ]]; then
-        printf "\033[0;36mdatamuse\033[0m says word \033[0;32m$sp\033[0m "
-        echo $CURL_RES | jq -j '.[] | @text "is pronounced like\(.tags[1]) (\(.tags[2])) \n"' | sed -E 's/[_]*pron:/ /g'
-    elif [[ $API = "owlbot" ]]; then
-        printf "\033[0;36mowlbot\033[0m says word \033[0;32m$sp\033[0m "
-        echo $CURL_RES | jq -j '.[] | @text "means \(.definition)\nexample: \(.example)\n"'
+        printf "\033[0;36mdatamuse\033[0m says word \033[0;32m${sp}\033[0m "
+        echo $curl_res | jq -j '.[].tags[] | capture("ipa_pron:(?<ipa>.*+)"),capture("^pron:(?<alpha>.+)")' | \
+            jq -s -r -M 'add | @text "is pronounced like \(.alpha) (ipa: \(.ipa))"'
+    elif [[ $api = "owlbot" ]]; then
+        if [[ $curl_res != "[]" ]]; then
+            printf "\033[0;36mowlbot\033[0m says word \033[0;32m$sp\033[0m "
+            echo $curl_res | jq -j '.[] | @text "means \(.definition)\nexample: \(.example)\n"'
+        fi
+        api="datamuse"
+        go_curl "https://api.datamuse.com/words?max=1&sp=${sp}&qe=sp&md=d&ipa=1"
+        printf "\033[0;36mdatamuse\033[0m says word \033[0;32m$sp\033[0m means\n"
+        echo $curl_res | jq -c -r '.[].defs[]'
     elif [[ -n $ml ]]; then
         printf "                                  \033[0;36mdatamuse thinks these words may help!\033[0m\n"
-        PLAIN_TEXT=$(printf %s "$CURL_RES"  | jq -j '.[] | @text "\(.word)\t\(.tags // [])\n"')
+        plain_text=$(printf %s "$curl_res"  | jq -j '.[] | @text "\(.word)\t\(.tags // [])\n"')
         IFS=$'\n\t'
-            printf "\033[0;32m%14s\033[0m %20s \033[0;32m%14s\033[0m %20s\n" $PLAIN_TEXT
+            printf "\033[0;32m%14s\033[0m %20s \033[0;32m%14s\033[0m %20s\n" $plain_text
         unset IFS
     else
         printf "                                  \033[0;36mdatamuse thinks these words may help!\033[0m\n"
-        PLAIN_TEXT=$(printf %s "$CURL_RES"  | jq -j '.[] | @text "\(.word) "')
-        printf "\033[0;32m%14s\033[0m \033[0;32m%14s\033[0m \033[0;32m%14s\033[0m \033[0;32m%14s\033[0m\n" $PLAIN_TEXT
+        plain_text=$(printf %s "$curl_res"  | jq -j '.[] | @text "\(.word) "')
+        printf "\033[0;32m%14s\033[0m \033[0;32m%14s\033[0m \033[0;32m%14s\033[0m \033[0;32m%14s\033[0m\n" $plain_text
     fi
     
     # The raw return JSON, passed through jq for highlighting
-    if [[ $VERBOSE -gt 2 ]]; then
-        echo $CURL_RES | jq -c
+    if [[ $verbose -gt 2 ]]; then
+        echo $curl_res | jq -c
     fi
 fi
 
